package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CiecleDetailImgMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ciecledetailimg
*/
public interface CiecleDetailImgMapper extends CiecleDetailImgMapperBase {
}