package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CircleCommentInfoMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circlecommentinfo
*/
public interface CircleCommentInfoMapper extends CircleCommentInfoMapperBase {
}