package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CircleCommentInfoAgreeMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circlecommentinfo_agree
*/
public interface CircleCommentInfoAgreeMapper extends CircleCommentInfoAgreeMapperBase {
}