package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CircleDetailInfoMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circledetailinfo
*/
public interface CircleDetailInfoMapper extends CircleDetailInfoMapperBase {
}