package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CityMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circleinfo
*/
public interface CityMapper extends CityMapperBase {
}