package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.CollectMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table collect
*/
public interface CollectMapper extends CollectMapperBase {
}