package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.beans.Comtocom;
import com.yizu.proj.sys.beans.ComtocomExample;
import com.yizu.proj.sys.dao.gen.ComtocomMapperBase;

import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comtocom
*/
public interface ComtocomMapper extends ComtocomMapperBase{
   
}