package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.FavoriteMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table favorite
*/
public interface FavoriteMapper extends FavoriteMapperBase {
}