package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.JoinVoteMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table joinvote
*/
public interface JoinVoteMapper extends JoinVoteMapperBase {
}