package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.MyVoteInfoImageMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo_image
*/
public interface MyVoteInfoImageMapper extends MyVoteInfoImageMapperBase {
}