package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.ProvinceMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circleinfo
*/
public interface ProvinceMapper extends ProvinceMapperBase {
}