package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.TagTopicMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tagtopic
*/
public interface TagTopicMapper extends TagTopicMapperBase {
}