package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.TfindPwdLogMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tfind_pwd_log
*/
public interface TfindPwdLogMapper extends TfindPwdLogMapperBase {
}