package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.TownMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circleinfo
*/
public interface TownMapper extends TownMapperBase {
}