package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.UserInfoMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
*/
public interface UserInfoMapper extends UserInfoMapperBase {
}