package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.UserCircleRlsMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_circle_rls
*/
public interface UserCircleRlsMapper extends UserCircleRlsMapperBase {
}