package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.VoteCommentInfoMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table votecommentinfo
*/
public interface VoteCommentInfoMapper extends VoteCommentInfoMapperBase {
}