package com.yizu.proj.sys.dao;

import com.yizu.proj.sys.dao.gen.YizubannerMapperBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public interface YizubannerMapper extends YizubannerMapperBase{
   
}