package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CiecleDetailImgExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ciecledetailimg
*/
public class CiecleDetailImgExample extends CiecleDetailImgExampleBase {
}