package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CircleDetailInfoExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circledetailinfo
*/
public class CircleDetailInfoExample extends CircleDetailInfoExampleBase {
}