package com.yizu.proj.sys.beans;


import com.yizu.proj.sys.beans.gen.CircleCommentInfoBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circlecommentinfo
*/
public class CircleCommentInfo extends CircleCommentInfoBase {
	/**创建圈子的用户信息*/
	private UserInfo userinfo;

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}
	
	
}