package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CirclerecommendBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class Circlerecommend extends CirclerecommendBase{
	private CircleInfo selectcircleinfo;

	public CircleInfo getSelectcircleinfo() {
		return selectcircleinfo;
	}

	public void setSelectcircleinfo(CircleInfo selectcircleinfo) {
		this.selectcircleinfo = selectcircleinfo;
	}
	
}