package com.yizu.proj.sys.beans;


import com.yizu.proj.sys.beans.gen.CircletagrelateBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class Circletagrelate extends CircletagrelateBase{

	private Circletag cirtag;

	public Circletag getCirtag() {
		return cirtag;
	}

	public void setCirtag(Circletag cirtag) {
		this.cirtag = cirtag;
	}
	
	
	
}