package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CircleInfoBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circleinfo
*/
public class CircleInfo extends CircleInfoBase {
	/**创建圈子的用户信息*/
	private UserInfo userinfo;
	/**当前用户是否已加入该圈子*/
	private String isjoin;
	
	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}

	public String getIsjoin() {
		return isjoin;
	}

	public void setIsjoin(String isjoin) {
		this.isjoin = isjoin;
	}
	
	
}