package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CircleCommentInfoAgreeExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circlecommentinfo_agree
*/
public class CircleCommentInfoAgreeExample extends CircleCommentInfoAgreeExampleBase {
}