package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CirclerecommendExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circledetailinfo
*/
public class CirclerecommendExample extends CirclerecommendExampleBase {
}