package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CityExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table circleinfo
*/
public class CityExample extends CityExampleBase {
}