package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.CollectExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table collect
*/
public class CollectExample extends CollectExampleBase {
}