package com.yizu.proj.sys.beans;

import java.util.Date;
import java.util.List;

import com.yizu.proj.sys.beans.gen.ComtocomBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comtocom
*/
public class Comtocom extends ComtocomBase{
	/**创建圈子的用户信息*/
	private UserInfo userinfo;
	
	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}
}