package com.yizu.proj.sys.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.yizu.proj.sys.beans.gen.ComtocomExampleBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comtocom
*/
public class ComtocomExample extends ComtocomExampleBase{
   
}