package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.FavoriteBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table favorite
*/
public class Favorite extends FavoriteBase {
}