package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.FavoriteExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table favorite
*/
public class FavoriteExample extends FavoriteExampleBase {
}