package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.JoinVoteBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table joinvote
*/
public class JoinVote extends JoinVoteBase {
	/**投票信息*/
	private MyVoteInfo myVoteInfo;

	public MyVoteInfo getMyVoteInfo() {
		return myVoteInfo;
	}

	public void setMyVoteInfo(MyVoteInfo myVoteInfo) {
		this.myVoteInfo = myVoteInfo;
	}
}