package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.JoinVoteExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table joinvote
*/
public class JoinVoteExample extends JoinVoteExampleBase {
}