package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.MyVoteInfoImageBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo_image
*/
public class MyVoteInfoImage extends MyVoteInfoImageBase {
}