package com.yizu.proj.sys.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.yizu.proj.sys.beans.gen.MyVoteInfoExampleBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class MyVoteInfoExample extends MyVoteInfoExampleBase {
	
}