package com.yizu.proj.sys.beans;

import java.util.List;

import com.yizu.proj.sys.beans.gen.MyVoteInfoBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class MyVoteInfo extends MyVoteInfoBase{
	private UserInfo userinfo;
	private List<MyVoteInfoImage> myVoteInfoImage;

	public List<MyVoteInfoImage> getMyVoteInfoImage() {
		return myVoteInfoImage;
	}

	public void setMyVoteInfoImage(List<MyVoteInfoImage> myVoteInfoImage) {
		this.myVoteInfoImage = myVoteInfoImage;
	}

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}
	
   
}