package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.TagTopicBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tagtopic
*/
public class TagTopic extends TagTopicBase {
}