package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.TagTopicExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tagtopic
*/
public class TagTopicExample extends TagTopicExampleBase {
}