package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.TfindPwdLogExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tfind_pwd_log
*/
public class TfindPwdLogExample extends TfindPwdLogExampleBase {
}