package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.TfindPwdLogBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tfind_pwd_log
*/
public class TfindPwdLog extends TfindPwdLogBase {
}