package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.UserCircleRlsExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_circle_rls
*/
public class UserCircleRlsExample extends UserCircleRlsExampleBase {
}