package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.UserInfoBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
*/
public class UserInfo extends UserInfoBase {
	public String userimage;
	public String userhobby;
	
	public String getUserhobby() {
		return userhobby;
	}

	public void setUserhobby(String userhobby) {
		this.userhobby = userhobby;
	}

	public String getUserimage() {
		return userimage;
	}

	public void setUserimage(String userimage) {
		this.userimage = userimage;
	}
	
}