package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.UserInfoExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
*/
public class UserInfoExample extends UserInfoExampleBase {
}