package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.VisitorBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class Visitor extends VisitorBase{
	private UserInfo userinfo;

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}
	

}