package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.VoteCommentInfoBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table votecommentinfo
*/
public class VoteCommentInfo extends VoteCommentInfoBase {
	/**评论的用户信息*/
	private UserInfo userinfo;

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}
	
}