package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.VoteCommentInfoExampleBase;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table votecommentinfo
*/
public class VoteCommentInfoExample extends VoteCommentInfoExampleBase {
	private String strSql;

	public String getStrSql() {
		return strSql;
	}

	public void setStrSql(String strSql) {
		this.strSql = strSql;
	}
}