package com.yizu.proj.sys.beans;

import com.yizu.proj.sys.beans.gen.YizubannerExampleBase;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table myvoteinfo
*/
public class YizubannerExample extends YizubannerExampleBase {
	
}